#!/usr/bin/env python3
"""
Network Devices Monitoring System
Ministry of Home Affairs, Lesotho
Uses only built-in Python libraries
"""

import subprocess
import platform
import json
import csv
from datetime import datetime
from typing import Dict, List, Tuple
import socket

# ========== CONFIGURATION ==========
DEVICES = {
    "computers": [
        {"name": "Front Desk PC", "ip": "8.8.8.8", "type": "windows"},
        {"name": "Registration PC", "ip": "1.1.1.1", "type": "windows"},
    ],
    "servers": [
        {"name": "NICR Database Server", "ip": "8.8.4.4", "type": "linux", "service": "postgresql"},
        {"name": "Web Server", "ip": "1.0.0.1", "type": "linux", "service": "nginx"},
    ],
    "switches": [
        {"name": "Core Switch", "ip": "8.8.8.8", "type": "switch"},
        {"name": "Access Switch 1", "ip": "1.1.1.1", "type": "switch"},
    ],
    "firewalls": [
        {"name": "Edge Firewall", "ip": "8.8.8.8", "type": "firewall"},
    ]
}

# Use public DNS for demo. Replace with actual IPs in production.

# ========== MONITORING FUNCTIONS ==========

def ping_device(ip: str, timeout: int = 2) -> Tuple[bool, float]:
    """Ping a device using system ping command"""
    param = '-n' if platform.system().lower() == 'windows' else '-c'
    command = ['ping', param, '1', '-w', str(timeout * 1000), ip]
    
    try:
        result = subprocess.run(command, capture_output=True, text=True, timeout=timeout)
        is_up = result.returncode == 0
        return is_up, None
    except Exception:
        return False, None


def check_remote_device(ip: str, device_name: str) -> Dict:
    """Check any remote device via ping"""
    is_up, _ = ping_device(ip)
    return {
        "name": device_name,
        "ip": ip,
        "is_up": is_up,
        "status": "Online" if is_up else "Offline",
        "timestamp": datetime.now().isoformat()
    }


def monitor_all_devices() -> Dict:
    """Monitor all configured devices"""
    results = {
        "timestamp": datetime.now().isoformat(),
        "devices": []
    }
    
    for category, devices in DEVICES.items():
        for device in devices:
            status = check_remote_device(device["ip"], device["name"])
            status["category"] = category
            results["devices"].append(status)
    
    return results


def generate_report(data: Dict) -> str:
    """Generate a formatted report"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report = []
    report.append("=" * 60)
    report.append("NETWORK DEVICES MONITORING REPORT")
    report.append("Ministry of Home Affairs, Lesotho")
    report.append(f"Generated: {timestamp}")
    report.append("=" * 60)
    
    # Group by category
    categorized = {}
    for device in data["devices"]:
        cat = device["category"]
        if cat not in categorized:
            categorized[cat] = []
        categorized[cat].append(device)
    
    icons = {"computers": "🖥️", "servers": "🖧", "switches": "🔌", "firewalls": "🛡️"}
    
    for cat, devices in categorized.items():
        icon = icons.get(cat, "📡")
        report.append(f"\n{icon} {cat.upper()}")
        for device in devices:
            status_icon = "🟢" if device["is_up"] else "🔴"
            report.append(f"   {status_icon} {device['name']}: {device['status']} ({device['ip']})")
    
    report.append(f"\n" + "=" * 60)
    report.append(f"Report generated by: Motlatsi Mosiuoa")
    report.append("=" * 60)
    
    return "\n".join(report)


def save_report_json(data: Dict):
    """Save report as JSON"""
    filename = f"network_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(filename, 'w') as f:
        json.dump(data, f, indent=2)
    return filename


def main():
    print("🔄 Starting network monitoring...")
    data = monitor_all_devices()
    report = generate_report(data)
    print(report)
    json_file = save_report_json(data)
    print(f"\n📁 Report saved: {json_file}")
    print("\n✅ Monitoring complete!")


if __name__ == "__main__":
    main()
